### PR TITLE
Custom API Installer

### PR DESCRIPTION
**Pull request by DirectXMan12**
This adds in a custom API installer that does just what's needed for the custom metrics API.
This way, we no longer need to depend on a patched version of `k8s.io/apiserver`.  On the downside, a lot of the helpers for the existing API installer are private, so they needed to be copied into the repository.

This also adds Glide files, to make it easy to install the required dependencies.

### CODE REVIEW

**Comment by DirectXMan12** [comment]
cc @luxas this is what I mentioned in kubernetes/kubernetes#42845

@kubernetes/sig-api-machinery-pr-reviews  if one of you has time, I wouldn't mind a quick sanity check on the hacked-up installer.

**Comment by DirectXMan12** [comment]
blech, group aliases don't seem to work in repos outside the org

@deads2k @liggitt this look roughly like what you'd expect?

**Comment by DirectXMan12** [comment]
(this should also give us a path to potentially supporting watch in the future, if we want, without too much work)

**Comment by DirectXMan12** [comment]
I'd like to get some unit tests in place, and then I'll merge this

**Comment by luxas** [comment]
I don't have time to review this line-by-line, but overall lgtm.
Also actually creating the vendor dir would be really cool, but that can be an other PR

I have some improvements in my fork and locally, but haven't had time to make something polished, ready-for-review of that yet.

**Comment by DirectXMan12** [comment]
merging, since I have unit tests in place and passing now.

**Pull request merged**
